# Generated by Django 6.1.1 on 2026-09-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="dealer_id",
        ),
    ]
